- name: install nginx
  ansible.builtin.dnf:
    name: nginx
    state: installed

- name: enable nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

- name: run requirements
  ansible.builtin.import_role:
    name: common
    tasks_from: requirements

# - name: remove default html file
#   ansible.builtin.file:
#     path: /usr/share/nginx/html/
#     state: absent

# - name: create html directory
#   ansible.builtin.file:
#     path: /usr/share/nginx/html/
#     state: directory

# - name: download & extract frontend content
#   ansible.builtin.unarchive:
#     src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
#     dest: /usr/share/nginx/html
#     remote_src: yes

- name: copy expense.conf
  ansible.builtin.template:
    src: expense.conf.j2
    dest: /etc/nginx/default.d/expense.conf
  notify:
  - restart nginx #this handler restart nginx service only when config changes.

# - name: restart nginx
#   ansible.builtin.service:
#     name: nginx
#     state: restarted